DIsk Collection Browser
josch1710/RespeQt pull request #4
Opened 2024-01-28 02:51 UTC by dcaputi1

The Disk Collection Browser (aka Disk Browser), allows the user to conveniently load and unload floppy disk image files with the click of the mouse from one simple dialog box. This creates a nostalgic approximation of the floppy disk flip files where an Atari user would commonly keep their collection of disks.

For more details refer to Disk-Collection-Browser.rtf in the RespeQr project root folder.

2024-01-29 07:45 UTC, josch1710 commented on include/miscutils.h
> +#if defined Q_OS_WIN
MacOS file systems are by default case insensitive. Please change that such that Linux is case sensitive and the rest not.

2024-01-29 07:47 UTC, josch1710 commented on include/miscutils.h
> +  #if !defined Q_OS_WIN
The same as above in the method osCaseSensitivity

2024-01-29 07:56 UTC, josch1710 commented on include/mainwindow.h
> +  void diskBrowserTriggered();   // what are all these trailing comment markers for?
I don't know. Perhaps a place holder for adding functionality comments in far future.

2024-01-29 08:51 UTC, josch1710 commented on src/mainwindow.cpp
> +    __debugbreak();
Does __debugbreak work on Linux, Macos, and Windows?

2024-01-29 08:55 UTC, josch1710 requested changes
I made some comments. Please fix that.

2024-01-29 09:12 UTC, josch1710 requested changes
Please review my comments.

2024-01-31 03:12 UTC, dcaputi1 commented on src/mainwindow.cpp
> +    __debugbreak();
It worked on my intel based MacBook but not sure that means all MacOS. First hit on stack overflow has an incomplete solution: https://stackoverflow.com/questions/173618/is-there-a-portable-equivalent-to-debugbreak-debugbreak
... not sure where to go with this.

2024-01-31 12:06 UTC, josch1710 approved these changes

2024-01-31 12:06 UTC, merged